sudo: false

language: c

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev

# The different configurations we want to test. You could also do things like
# change flags or use --stack-yaml to point to a different file.
env:
- ARGS="--resolver lts-7"
- ARGS="--resolver lts-8"
- ARGS="--resolver lts-9.21" # 8.0.2
- ARGS="--resolver lts-10.7"
- ARGS="--resolver lts-12.11"
- ARGS="--resolver lts-12.14" # 8.4.3
- ARGS="--resolver lts-12.26" # 8.4.4
- ARGS="--resolver lts-13.25"
- ARGS="--resolver lts"
- ARGS="--resolver nightly"

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script: stack $ARGS --no-terminal --install-ghc test --haddock

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
